onlyBuiltDependencies:
  - esbuild
  - tree-sitter
  - tree-sitter-javascript
  - tree-sitter-typescript
minimumReleaseAgeExclude:
  - '@effect/platform-node-shared@4.0.2'
  - '@effect/platform-node@4.0.2'
  - effect@4.0.2
  - '@effect/vitest@4.0.2'
