import { createHash } from "node:crypto"
import type { Finding } from "./model.js"

/** GitHub rejects comments above 65,536 characters; leave room for multibyte text. */
export const maxCommentBytes = 60_000

export const parsePullRequest = (value: string) => {
  const match = /^https:\/\/github\.com\/([a-zA-Z0-9-]+)\/([a-zA-Z0-9_.-]+)\/pull\/([1-9]\d*)\/?$/.exec(value)
  if (!match || [".", ".."].includes(match[2]!) || !Number.isSafeInteger(Number(match[3]))) {
    throw new Error("Use a full PR URL: https://github.com/OWNER/REPO/pull/NUMBER.")
  }
  return { repository: `${match[1]}/${match[2]}`, number: Number(match[3]), url: `https://github.com/${match[1]}/${match[2]}/pull/${match[3]}` }
}

/** The published content of one review. The CLI previews it or posts it as the Benedict GitHub App. */
export interface PublishedReview {
  readonly base: string
  readonly head: string
  readonly organizationRevision: string | null
  readonly findings: ReadonlyArray<Finding>
  readonly dropped: number
  readonly confidence: number
  readonly context: string
}

/** One finding anchored to head-side lines of the PR diff. */
export interface InlineComment {
  readonly path: string
  readonly startLine: number
  readonly line: number
  readonly body: string
}

/** A GitHub PR review: a summary body plus one inline comment per finding that lands on the diff. */
export interface RenderedReview {
  readonly body: string
  readonly comments: ReadonlyArray<InlineComment>
}

/** Identifies a review's content, so a rerun finds the review it already posted. */
export const reviewMarker = (review: PublishedReview) => {
  const { base, head, organizationRevision, findings, dropped, confidence, context } = review
  const digest = createHash("sha256").update(JSON.stringify([base, head, organizationRevision, findings, dropped, confidence, context])).digest("hex")
  return `<!-- benedict:review:v1 ${digest} -->`
}

const plain = (text: string) => text.replace(/[\r\n]/g, " ").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/([\\`*_{}\[\]()#!|])/g, "\\$1")
const encodePath = (file: string) => file.split("/").map((part) => encodeURIComponent(part).replace(/[!'()*]/g, (char) => `%${char.charCodeAt(0).toString(16)}`)).join("/")
const quoteBlock = (quote: string) => {
  let width = 3
  for (const match of quote.matchAll(/`+/g)) width = Math.max(width, match[0].length + 1)
  const fence = "`".repeat(width)
  return `${fence}\n${quote}\n${fence}`
}

/** Head-side line ranges of each hunk in a unified diff patch from GitHub's PR files API. */
export const hunkRanges = (patch: string): ReadonlyArray<readonly [number, number]> =>
  [...patch.matchAll(/^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@/gm)].flatMap((match) => {
    const start = Number(match[1]), count = match[2] === undefined ? 1 : Number(match[2])
    return count > 0 ? [[start, start + count - 1] as const] : []
  })

/** GitHub only accepts review comments on diff lines; anchor to the first hunk the finding overlaps. */
const anchor = (finding: Finding, patches: ReadonlyMap<string, string>) => {
  for (const [first, last] of hunkRanges(patches.get(finding.file) ?? "")) {
    const startLine = Math.max(first, finding.startLine), line = Math.min(last, finding.endLine)
    if (startLine <= line) return { startLine, line }
  }
  return undefined
}

const findingHeader = (finding: Finding) => `**${finding.severity} · ${finding.skill}** · confidence ${finding.confidence}`

const inlineBody = (finding: Finding) => [
  `### ${plain(finding.title)}`,
  findingHeader(finding),
  finding.explanation,
  ...(finding.suggestedFix === undefined ? [] : [`Suggested fix: ${finding.suggestedFix}`]),
  "<sub>AI-generated by Benedict.</sub>"
].join("\n\n") + "\n"

/** Renders the review against the PR's file patches, keyed by head path. */
export const renderReview = (review: PublishedReview, repository: string, patches: ReadonlyMap<string, string>): RenderedReview => {
  const comments: InlineComment[] = []
  const outside: Finding[] = []
  for (const finding of review.findings) {
    const range = anchor(finding, patches)
    if (range === undefined) outside.push(finding)
    else comments.push({ path: finding.file, ...range, body: inlineBody(finding) })
  }
  const body = [
    reviewMarker(review),
    "## AI-generated review",
    "Generated by **Benedict**, the automated review skill and CLI. A developer's local AI agent wrote this review and the Benedict GitHub App posted it; it does not indicate human authorship.",
    `Reviewed commits: \`${review.base}\` → \`${review.head}\`.`,
    ...(review.organizationRevision ? [`Organization knowledge revision: \`${review.organizationRevision}\`.`] : []),
    `Accepted findings: **${review.findings.length}** (${comments.length} inline). Dropped drafts: **${review.dropped}**.`,
    `Overall confidence: **${review.confidence}/5**.`,
    ...(review.findings.length === 0 ? ["The review found nothing that cleared the configured evidence and policy bar."] : []),
    ...(outside.length === 0 ? [] : ["### Findings outside the diff"]),
    ...outside.map((finding, index) => [
      `#### ${index + 1}. ${plain(finding.title)}`,
      findingHeader(finding),
      `[${plain(finding.file)}:${finding.startLine}-${finding.endLine}](https://github.com/${repository}/blob/${review.head}/${encodePath(finding.file)}#L${finding.startLine}-L${finding.endLine})`,
      finding.explanation,
      quoteBlock(finding.quote),
      ...(finding.suggestedFix === undefined ? [] : [`Suggested fix: ${finding.suggestedFix}`])
    ].join("\n\n")),
    ...(review.context.trim() ? ["### Review context", review.context.trim()] : []),
    "Source evidence and policy were checked by the CLI. Defect assessment and additional context are supplied by the AI reviewer."
  ].join("\n\n") + "\n"
  return { body, comments }
}

/** Returns a message when any part of the review exceeds GitHub's comment size limit. */
export const oversized = (rendered: RenderedReview): string | undefined => {
  if (Buffer.byteLength(rendered.body, "utf8") > maxCommentBytes) return `The review summary exceeds ${maxCommentBytes} bytes.`
  const comment = rendered.comments.find((item) => Buffer.byteLength(item.body, "utf8") > maxCommentBytes)
  return comment && `The inline comment on ${comment.path}:${comment.line} exceeds ${maxCommentBytes} bytes.`
}
