import type { Finding } from "./model.js"

export const commentMarker = "<!-- benedict:automated-reviewer:v1 -->"
/** GitHub rejects comments above 65,536 characters; leave room for multibyte text. */
export const maxCommentBytes = 60_000

export const parsePullRequest = (value: string) => {
  const match = /^https:\/\/github\.com\/([a-zA-Z0-9-]+)\/([a-zA-Z0-9_.-]+)\/pull\/([1-9]\d*)\/?$/.exec(value)
  if (!match || [".", ".."].includes(match[2]!) || !Number.isSafeInteger(Number(match[3]))) {
    throw new Error("Use a full PR URL: https://github.com/OWNER/REPO/pull/NUMBER.")
  }
  return { repository: `${match[1]}/${match[2]}`, number: Number(match[3]), url: `https://github.com/${match[1]}/${match[2]}/pull/${match[3]}` }
}

/** The published content of one review. The CLI previews it and the Benedict service posts it. */
export interface PublishedReview {
  readonly base: string
  readonly head: string
  readonly organizationRevision: string | null
  readonly findings: ReadonlyArray<Finding>
  readonly dropped: number
  readonly confidence: number
  readonly context: string
}

const plain = (text: string) => text.replace(/[\r\n]/g, " ").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/([\\`*_{}\[\]()#!|])/g, "\\$1")
const encodePath = (file: string) => file.split("/").map((part) => encodeURIComponent(part).replace(/[!'()*]/g, (char) => `%${char.charCodeAt(0).toString(16)}`)).join("/")
const quoteBlock = (quote: string) => {
  let width = 3
  for (const match of quote.matchAll(/`+/g)) width = Math.max(width, match[0].length + 1)
  const fence = "`".repeat(width)
  return `${fence}\n${quote}\n${fence}`
}

export const renderComment = (review: PublishedReview, repository: string): string => [
  commentMarker,
  "## AI-generated review",
  "Generated by **Benedict**, the automated review skill and CLI. A developer's local AI agent wrote this review and the Benedict GitHub App posted it; it does not indicate human authorship.",
  `Reviewed commits: \`${review.base}\` → \`${review.head}\`.`,
  ...(review.organizationRevision ? [`Organization knowledge revision: \`${review.organizationRevision}\`.`] : []),
  `Accepted findings: **${review.findings.length}**. Dropped drafts: **${review.dropped}**.`,
  `Overall confidence: **${review.confidence}/5**.`,
  ...(review.findings.length === 0 ? ["The review found nothing that cleared the configured evidence and policy bar."] : []),
  ...review.findings.map((finding, index) => [
    `### ${index + 1}. ${plain(finding.title)}`,
    `**${finding.severity} · ${finding.skill}** · confidence ${finding.confidence}`,
    `[${plain(finding.file)}:${finding.startLine}-${finding.endLine}](https://github.com/${repository}/blob/${review.head}/${encodePath(finding.file)}#L${finding.startLine}-L${finding.endLine})`,
    finding.explanation,
    quoteBlock(finding.quote),
    ...(finding.suggestedFix === undefined ? [] : [`Suggested fix: ${finding.suggestedFix}`])
  ].join("\n\n")),
  ...(review.context.trim() ? ["### Review context", review.context.trim()] : []),
  "Source evidence and policy were checked by the CLI. Defect assessment and additional context are supplied by the AI reviewer."
].join("\n\n") + "\n"
