import { Effect, FileSystem, Schema } from "effect"
import { checkFindings, readFindings } from "./check.js"
import { collectSnapshot } from "./context.js"
import { Git } from "./git.js"
import { GitHub } from "./github.js"
import { ReviewError } from "./model.js"
import type { CheckReport } from "./model.js"

export const commentMarker = "<!-- benedict:automated-reviewer:v1 -->"
const PositiveInt = Schema.Int.check(Schema.isGreaterThanOrEqualTo(1))
const Sha = Schema.String.check(Schema.makeFilter((value) => /^[a-f0-9]{40}$/.test(value)))
const PullRequest = Schema.Struct({ state: Schema.Literals(["open", "closed"]), head: Schema.Struct({ sha: Sha }), base: Schema.Struct({ sha: Sha }) })
const User = Schema.Struct({ id: PositiveInt })
const Comment = Schema.Struct({ id: PositiveInt, html_url: Schema.String, body: Schema.NullOr(Schema.String), user: User })

export interface PublishOptions {
  readonly findings: string
  readonly pr: string
  readonly repo: string
  readonly base?: string
  readonly head?: string
  readonly config?: string
  readonly contextFile?: string
  readonly dryRun: boolean
}

export const parsePullRequest = (value: string) => {
  const match = /^https:\/\/github\.com\/([a-zA-Z0-9-]+)\/([a-zA-Z0-9_.-]+)\/pull\/([1-9]\d*)\/?$/.exec(value)
  if (!match || [".", ".."].includes(match[2]!) || !Number.isSafeInteger(Number(match[3]))) {
    throw new Error("Use a full PR URL: https://github.com/OWNER/REPO/pull/NUMBER.")
  }
  return { repository: `${match[1]}/${match[2]}`, number: Number(match[3]), url: `https://github.com/${match[1]}/${match[2]}/pull/${match[3]}` }
}

const plain = (text: string) => text.replace(/[\r\n]/g, " ").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/([\\`*_{}\[\]()#!|])/g, "\\$1")
const encodePath = (file: string) => file.split("/").map((part) => encodeURIComponent(part).replace(/[!'()*]/g, (char) => `%${char.charCodeAt(0).toString(16)}`)).join("/")
const quoteBlock = (quote: string) => {
  let width = 3
  for (const match of quote.matchAll(/`+/g)) width = Math.max(width, match[0].length + 1)
  const fence = "`".repeat(width)
  return `${fence}\n${quote}\n${fence}`
}

export const renderComment = (report: CheckReport, repository: string, context?: string): string => [
  commentMarker,
  "## AI-generated review",
  "Generated by **Benedict**, the automated review skill and CLI. The signed-in GitHub account posts this AI-generated content; it does not indicate human authorship.",
  `Reviewed commits: \`${report.range.base}\` → \`${report.range.head}\`.`,
  ...(report.organization ? [`Organization knowledge revision: \`${report.organization.revision}\`.`] : []),
  `Accepted findings: **${report.summary.accepted}**. Dropped drafts: **${report.summary.rejected}**.`,
  ...(report.accepted.length === 0 ? ["The review found nothing that cleared the configured evidence and policy bar."] : []),
  ...report.accepted.map((finding, index) => [
    `### ${index + 1}. ${plain(finding.title)}`,
    `**${finding.severity} · ${finding.skill}** · confidence ${finding.confidence}`,
    `[${plain(finding.file)}:${finding.startLine}-${finding.endLine}](https://github.com/${repository}/blob/${report.range.head}/${encodePath(finding.file)}#L${finding.startLine}-L${finding.endLine})`,
    finding.explanation,
    quoteBlock(finding.quote),
    ...(finding.suggestedFix === undefined ? [] : [`Suggested fix: ${finding.suggestedFix}`])
  ].join("\n\n")),
  ...(context?.trim() ? ["### Review context", context.trim()] : []),
  "Source evidence and policy were checked by the CLI. Defect assessment and additional context are supplied by the AI reviewer."
].join("\n\n") + "\n"

const decode = <S extends Schema.Top>(schema: S, value: unknown) => Schema.decodeUnknownEffect(schema)(value).pipe(
  Effect.mapError(() => new ReviewError({ code: "github_error", message: "GitHub returned an unexpected response; no further writes were attempted." }))
)

export const publishReview = Effect.fn("Review.publish")(function*(options: PublishOptions) {
  const target = yield* Effect.try({
    try: () => parsePullRequest(options.pr),
    catch: (error) => new ReviewError({ code: "input_error", message: String(error) })
  })
  const drafts = yield* readFindings(options.findings)
  const fs = yield* FileSystem.FileSystem
  const context = options.contextFile === undefined ? undefined : yield* fs.readFileString(options.contextFile)
  const gh = yield* GitHub
  const git = yield* Git
  const endpoint = `repos/${target.repository}/pulls/${target.number}`
  const pr = yield* decode(PullRequest, yield* gh.request("GET", endpoint))
  if (pr.state !== "open") return yield* new ReviewError({ code: "pr_closed", message: "The target PR is closed." })
  const resolveMergeBase = git.run(options.repo, ["merge-base", pr.base.sha, pr.head.sha]).pipe(
    Effect.map((value) => value.trim()),
    Effect.mapError(() => new ReviewError({ code: "range_error", message: "Cannot resolve the PR merge base locally. Run benedict context --pr to fetch the PR commits, or fetch them manually, before retrying." }))
  )
  const base = options.base ?? (yield* resolveMergeBase)
  const snapshot = yield* collectSnapshot({ repo: options.repo, base, head: options.head, config: options.config, worktree: false })
  const report = yield* checkFindings(snapshot, drafts)
  if (report.range.head !== pr.head.sha) {
    return yield* new ReviewError({ code: "stale_review", message: `Reviewed head ${report.range.head} differs from PR head ${pr.head.sha}. Review the current PR head before publishing.` })
  }
  const ancestor = (yield* git.run(snapshot.context.repository, ["merge-base", report.range.base, pr.head.sha])).trim()
  if (ancestor !== report.range.base) return yield* new ReviewError({ code: "range_error", message: "Reviewed base must be an ancestor of the PR head." })
  const prMergeBase = options.base === undefined ? base : yield* resolveMergeBase
  const sharedBase = (yield* git.run(snapshot.context.repository, ["merge-base", prMergeBase, report.range.base])).trim()
  if (sharedBase !== prMergeBase) return yield* new ReviewError({ code: "range_error", message: "Reviewed base is outside the PR range. Use the PR merge base or a later ancestor of its head." })
  const body = renderComment(report, target.repository, context)
  if (Buffer.byteLength(body, "utf8") > 60_000) {
    return yield* new ReviewError({ code: "comment_too_large", message: "Review comment exceeds 60,000 bytes. Shorten findings or context before publishing." })
  }
  const result = { formatVersion: 1 as const, pr: target.url, range: report.range, organization: report.organization, summary: report.summary, body }
  if (options.dryRun) return { ...result, action: "dry-run" as const, commentUrl: null }

  const user = yield* decode(User, yield* gh.request("GET", "user"))
  const matching: Array<typeof Comment.Type> = []
  for (let page = 1; ; page++) {
    const comments = yield* decode(Schema.Array(Comment), yield* gh.request("GET", `repos/${target.repository}/issues/${target.number}/comments?per_page=100&page=${page}`))
    matching.push(...comments.filter((comment) => comment.user.id === user.id && comment.body?.startsWith(`${commentMarker}\n`)))
    if (comments.length < 100) break
  }
  if (matching.length > 1) return yield* new ReviewError({ code: "ambiguous_comment", message: "Multiple automated review comments from this account exist. Resolve the duplicates before publishing." })
  // Re-read after validation and pagination, immediately before the possible write.
  const current = yield* decode(PullRequest, yield* gh.request("GET", endpoint))
  if (current.state !== "open" || current.head.sha !== pr.head.sha || current.base.sha !== pr.base.sha) {
    return yield* new ReviewError({ code: "stale_review", message: "The PR changed during publication. Review its current range before retrying." })
  }
  const existing = matching[0]
  if (existing?.body === body) return { ...result, action: "unchanged" as const, commentUrl: existing.html_url }
  const written = yield* decode(Comment, yield* gh.request(
    existing === undefined ? "POST" : "PATCH",
    existing === undefined ? `repos/${target.repository}/issues/${target.number}/comments` : `repos/${target.repository}/issues/comments/${existing.id}`,
    { body }
  ))
  return { ...result, action: existing === undefined ? "created" as const : "updated" as const, commentUrl: written.html_url }
})
